added mongo/spring tests recognition into this branch

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -10,43 +10,43 @@ name: Java CI with Maven
 
 on:
   push:
-    branches: 
-    - '**'
+    branches:
+      - '**'
   pull_request:
     branches:
-    - '**'
+      - '**'
 
 # pray this works bro.
 permissions:
-    contents: read
-    checks: write
-    id-token: write    
+  contents: read
+  checks: write
+  id-token: write
 
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
-    - name: 'Create env file'
-      run: echo "${{ secrets.ENV_FILE }}" > .env
-    - name: Set up JDK 20
-      uses: actions/setup-java@v3
-      with:
-        java-version: '17'
-        distribution: 'temurin'
-        cache: maven
-    - name: Start MongoDB
-      uses: supercharge/mongodb-github-action@1.8.0
-      with:
-        mongodb-version: '6.0'
-    - name: Test with Maven
-      run: mvn -B surefire-report:report --file pom.xml -Dmaven.test.failure.ignore=true
+      - uses: actions/checkout@v3
+      - name: 'Create env file'
+        run: echo "${{ secrets.ENV_FILE }}" > .env
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+          cache: maven
+      - name: Start MongoDB
+        uses: supercharge/mongodb-github-action@1.8.0
+        with:
+          mongodb-version: '6.0'
+      - name: Test with Maven
+        run: mvn -B surefire-report:report --file pom.xml -Dmaven.test.failure.ignore=true
 
-# report the results, from lab 2
-    - name: Publish Test Report
-      uses: mikepenz/action-junit-report@v3
-      if: success() || failure() # always run even if the previous step fails
-      with:
-        report_paths: '**/target/surefire-reports/TEST-*.xml'
-        detailed_summary: true # display detailed summary of the report
-        include_passed: true # include passed tests in the results table
+      # report the results, from lab 2
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/target/surefire-reports/TEST-*.xml'
+          detailed_summary: true # display detailed summary of the report
+          include_passed: true # include passed tests in the results table
